algo = input('Digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(algo)))
print('É alfabético? {}'.format(algo.isalpha()))
print('É alfanumérico? {}'.format(algo.isalnum()))
print('É minúsculo? {}'.format(algo.islower()))
print('É maiúsculo? {}'.format(algo.isupper()))
print('É número? {}'.format(algo.isnumeric()))
print('É decimal? {}'.format((algo.isdecimal())))
print('Só tem espaço? {}'.format(algo.isspace()))
